// src/components/admin/AdminDashboard.tsx
import { BlogPostMeta } from "../../types";

interface BuildStatus {
  status: "building" | "ready" | "error" | "queued" | "unknown";
  commit_message?: string;
  created_at?: string;
}

interface AdminDashboardProps {
  posts: BlogPostMeta[];
  loading: boolean;
  error?: string;
  success?: string;
  buildStatus?: BuildStatus | null;
  dataSource?: "cache" | "github";
  onEdit: (post: BlogPostMeta) => void;
  onDelete: (filename: string) => void;
  onCreate: () => void;
  onLogout: () => void;
  onRefresh: () => void;
}

export default function AdminDashboard({ 
  posts, 
  loading,
  error,
  success,
  buildStatus,
  dataSource,
  onEdit, 
  onDelete, 
  onCreate, 
  onLogout,
  onRefresh,
}: AdminDashboardProps) {
  const getBuildStatusColor = () => {
    switch (buildStatus?.status) {
      case "building":
      case "queued":
        return "#f59e0b"; // amber
      case "ready":
        return "#10b981"; // green
      case "error":
        return "#ef4444"; // red
      default:
        return "#6b7280"; // gray
    }
  };

  const getBuildStatusText = () => {
    switch (buildStatus?.status) {
      case "building":
        return "Building...";
      case "queued":
        return "Queued";
      case "ready":
        return "Live";
      case "error":
        return "Build Failed";
      default:
        return "Unknown";
    }
  };

  return (
    <div className="admin-container">
      <header className="admin-header">
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <h1 className="admin-title" style={{ fontSize: '1.5rem', margin: 0 }}>Content Manager</h1>
          <span style={{ 
            background: 'rgba(94, 234, 212, 0.2)', 
            color: 'var(--color-navy)', 
            padding: '0.25rem 0.75rem', 
            borderRadius: '999px',
            fontSize: '0.75rem',
            fontWeight: 700
          }}>
            {posts.length} Posts
          </span>
          {buildStatus && (
            <span style={{ 
              background: `${getBuildStatusColor()}20`,
              color: getBuildStatusColor(),
              padding: '0.25rem 0.75rem', 
              borderRadius: '999px',
              fontSize: '0.75rem',
              fontWeight: 700,
              display: 'flex',
              alignItems: 'center',
              gap: '0.5rem'
            }}>
              {(buildStatus.status === "building" || buildStatus.status === "queued") && (
                <span style={{
                  width: '8px',
                  height: '8px',
                  borderRadius: '50%',
                  background: getBuildStatusColor(),
                  animation: 'pulse 1.5s infinite'
                }} />
              )}
              {getBuildStatusText()}
            </span>
          )}
        </div>
        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <button 
            onClick={onRefresh} 
            className="btn-outline btn-sm"
            disabled={loading}
            title="Fetch latest posts from GitHub"
          >
            ↻ Refresh
          </button>
          <button onClick={onCreate} className="admin-btn btn-sm">
            + New Post
          </button>
          <a href="/" className="btn-outline" style={{ textDecoration: 'none', display: 'flex', alignItems: 'center' }}>
            View Site
          </a>
          <button onClick={onLogout} className="btn-outline">
            Logout
          </button>
        </div>
      </header>

      {/* Data Source Indicator */}
      {dataSource && (
        <div style={{
          padding: '0.5rem 2rem',
          fontSize: '0.75rem',
          color: 'var(--color-periwinkle)',
          borderBottom: '1px solid rgba(0,0,0,0.05)'
        }}>
          Data source: <strong>{dataSource === 'github' ? '🔄 Live from GitHub' : '📦 Cached (last build)'}</strong>
          {dataSource === 'cache' && (
            <span style={{ marginLeft: '0.5rem' }}>
              — <button onClick={onRefresh} style={{ 
                background: 'none', 
                border: 'none', 
                color: 'var(--color-teal)', 
                cursor: 'pointer',
                textDecoration: 'underline',
                padding: 0,
                font: 'inherit'
              }}>Load fresh data</button>
            </span>
          )}
        </div>
      )}

      {/* Success Message */}
      {success && (
        <div style={{
          background: 'rgba(94, 234, 212, 0.15)',
          border: '1px solid var(--color-teal)',
          color: 'var(--color-navy)',
          padding: '1rem 1.5rem',
          margin: '1rem 2rem 0',
          borderRadius: '8px',
          display: 'flex',
          alignItems: 'center',
          gap: '0.75rem'
        }}>
          <span style={{ fontSize: '1.25rem' }}>✓</span>
          <div>
            <strong>{success}</strong>
            {buildStatus?.status === "building" && (
              <div style={{ fontSize: '0.85rem', opacity: 0.8, marginTop: '0.25rem' }}>
                Site is rebuilding. Changes will be live in ~1-2 minutes.
              </div>
            )}
          </div>
        </div>
      )}

      {/* Error Message */}
      {error && (
        <div style={{
          background: 'rgba(239, 68, 68, 0.1)',
          border: '1px solid #ef4444',
          color: '#dc2626',
          padding: '1rem 1.5rem',
          margin: '1rem 2rem 0',
          borderRadius: '8px',
        }}>
          <strong>Error:</strong> {error}
        </div>
      )}

      <main className="admin-content">
        {loading ? (
          <div style={{ textAlign: 'center', padding: '4rem', color: 'var(--color-periwinkle)' }}>
            <div style={{ 
              display: 'inline-block',
              width: '24px',
              height: '24px',
              border: '3px solid rgba(94, 234, 212, 0.3)',
              borderTopColor: 'var(--color-teal)',
              borderRadius: '50%',
              animation: 'spin 1s linear infinite',
              marginBottom: '1rem'
            }} />
            <div>Loading content...</div>
          </div>
        ) : posts.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '4rem', color: 'var(--color-periwinkle)' }}>
            No posts found. Create your first blog post to get started.
          </div>
        ) : (
          <div className="post-grid">
            {posts.map((post) => (
              <div key={post.filename || post.slug} className="post-card">
                <h3 className="post-card-title">{post.title}</h3>
                <div className="post-card-meta">
                  {post.date} • {post.category}
                </div>
                <p className="post-card-desc">
                  {post.description || "No description provided."}
                </p>
                <div className="post-card-actions">
                  <button onClick={() => onEdit(post)} className="admin-btn btn-sm" style={{ flex: 1 }}>
                    Edit
                  </button>
                  <button onClick={() => onDelete(post.filename)} className="btn-danger btn-sm">
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </main>

      <style>{`
        @keyframes spin {
          to { transform: rotate(360deg); }
        }
        @keyframes pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.5; }
        }
      `}</style>
    </div>
  );
}

// solidjs_bun_version/src/components/admin/AdminDashboard.tsx
import { For, Show } from "solid-js";
import { BlogPostMeta } from "~/types";

interface BuildStatus {
  status: "building" | "ready" | "error" | "queued" | "unknown";
  commit_message?: string;
  created_at?: string;
}

interface AdminDashboardProps {
  posts: BlogPostMeta[];
  loading: boolean;
  error: string;
  success: string;
  buildStatus: BuildStatus | null;
  dataSource: "cache" | "github";
  onEdit: (post: BlogPostMeta) => void;
  onDelete: (filename: string) => void;
  onCreate: () => void;
  onLogout: () => void;
  onRefresh: () => void;
}

export default function AdminDashboard(props: AdminDashboardProps) {
  const getStatusColor = () => {
    switch (props.buildStatus?.status) {
      case "building": return "#fbbf24"; // amber
      case "ready": return "#10b981"; // green
      case "error": return "#ef4444"; // red
      case "queued": return "#3b82f6"; // blue
      default: return "#64748b"; // gray
    }
  };

  const getStatusText = () => {
    switch (props.buildStatus?.status) {
      case "building": return "Building...";
      case "ready": return "Ready";
      case "error": return "Error";
      case "queued": return "Queued";
      default: return "Unknown";
    }
  };

  return (
    <div class="admin-container">
      <div class="admin-header">
        <div>
          <h2 class="admin-title">Admin Dashboard</h2>
          <p class="admin-subtitle">Manage your blog content</p>
        </div>
        <div style={{ display: "flex", gap: "1rem", "align-items": "center" }}>
          <Show when={props.buildStatus}>
            <div style={{
              display: "flex",
              "align-items": "center",
              gap: "0.5rem",
              padding: "0.5rem 1rem",
              "border-radius": "4px",
              background: "rgba(45, 42, 94, 0.05)",
              border: `1px solid ${getStatusColor()}`
            }}>
              <div style={{
                width: "12px",
                height: "12px",
                "border-radius": "50%",
                background: getStatusColor()
              }}></div>
              <span style={{ "font-size": "0.875rem", color: getStatusColor() }}>
                {getStatusText()}
              </span>
            </div>
          </Show>
          <button onClick={props.onRefresh} class="btn-outline" style={{ "font-size": "0.875rem" }}>
            Refresh Posts
          </button>
          <button onClick={props.onCreate} class="btn" style={{ "font-size": "0.875rem" }}>
            New Post
          </button>
          <button onClick={props.onLogout} class="btn-danger" style={{ "font-size": "0.875rem" }}>
            Logout
          </button>
        </div>
      </div>

      <div class="admin-content">
        <Show when={props.success}>
          <div style={{
            background: "#dcfce7",
            color: "#166534",
            padding: "1rem",
            "border-radius": "8px",
            "margin-bottom": "1rem",
            border: "1px solid #bbf7d0"
          }}>
            {props.success}
          </div>
        </Show>

        <Show when={props.error}>
          <div style={{
            background: "#fee2e2",
            color: "#991b1b",
            padding: "1rem",
            "border-radius": "8px",
            "margin-bottom": "1rem",
            border: "1px solid #fecaca"
          }}>
            {props.error}
          </div>
        </Show>

        <div style={{ display: "flex", "justify-content": "space-between", "align-items": "center", "margin-bottom": "1rem" }}>
          <h3 style={{ "font-size": "1.125rem", "font-weight": "600" }}>Blog Posts</h3>
          <span style={{ "font-size": "0.875rem", color: "#64748b" }}>
            Data Source: {props.dataSource === "github" ? "GitHub" : "Cache"}
          </span>
        </div>

        <Show when={props.loading} fallback={
          <>
            <Show when={props.posts.length > 0} fallback={
              <div style={{ "text-align": "center", padding: "4rem", color: "#64748b" }}>
                <p>No posts found. Create your first post!</p>
              </div>
            }>
              <div class="post-grid">
                <For each={props.posts}>
                  {(post) => (
                    <div class="post-card">
                      <div style={{ display: "flex", "justify-content": "space-between", "align-items": "flex-start", "margin-bottom": "0.5rem" }}>
                        <h4 class="post-card-title">{post.title}</h4>
                        <span style={{ "font-size": "0.75rem", color: "#64748b", "font-family": "var(--font-mono)" }}>
                          {post.category}
                        </span>
                      </div>
                      <p class="post-card-meta">{post.date} • {post.readTime}</p>
                      <p class="post-card-desc">{post.description}</p>
                      <div class="post-card-actions">
                        <button onClick={() => props.onEdit(post)} class="btn-sm btn-outline">
                          Edit
                        </button>
                        <button onClick={() => props.onDelete(post.filename)} class="btn-sm btn-danger">
                          Delete
                        </button>
                      </div>
                    </div>
                  )}
                </For>
              </div>
            </Show>
          </>
        }>
          <div style={{ "text-align": "center", padding: "4rem" }}>
            <p>Loading posts...</p>
          </div>
        </Show>
      </div>
    </div>
  );
}
